apiVersion: v1
kind: Secret
metadata:
  name: {{ include "athena-server.fullname" . }}-secrets
  labels:
    {{- include "athena-server.labels" . | nindent 4 }}
type: Opaque
data:
  auth-token: {{ .Values.auth.token | b64enc | quote }}
  openai-api-key: {{ .Values.openai.apiKey | b64enc | quote }}
  athena-tts-token: {{ .Values.athenaTts.token | b64enc | quote }}
